// AUTO-GENERATED by scripts/generate-allocations.mjs — do not hand-edit.
// Source: data/Allocations-ac6fc2.xlsx

export type InternationalRow = { class: string; name: string; country: string }
export type NationalRow = { name: string; delegation: string; party: string }

export const internationalAllocations: Record<string, InternationalRow[]> = {
  "hrc": [
    {
      "class": "9A",
      "name": "Anuj Jung Thapa",
      "country": "Afghanistan"
    },
    {
      "class": "9A",
      "name": "Sarjan Lamichhane",
      "country": "USA"
    },
    {
      "class": "9A",
      "name": "Samyog Sedhai",
      "country": "China"
    },
    {
      "class": "9A",
      "name": "Eva Shakya",
      "country": "Egypt"
    },
    {
      "class": "9A",
      "name": "Aashutosh Poudel",
      "country": "Germany"
    },
    {
      "class": "9A",
      "name": "Kripa Thapaliya",
      "country": "Lebanon"
    },
    {
      "class": "9A",
      "name": "Nirman Ghimire",
      "country": "Indonesia"
    },
    {
      "class": "9A",
      "name": "Samunnat Burlakoti",
      "country": "Isreal"
    },
    {
      "class": "9B",
      "name": "Prasiddha Neupane",
      "country": "Russia"
    },
    {
      "class": "9B",
      "name": "Naman B.C.",
      "country": "North Korea"
    },
    {
      "class": "9B",
      "name": "Agrim Pandey",
      "country": "Nepal"
    },
    {
      "class": "9B",
      "name": "Eurosh Maharjan",
      "country": "Palestine"
    },
    {
      "class": "9B",
      "name": "Ojaswi Pant",
      "country": "Pakistan"
    },
    {
      "class": "9B",
      "name": "Seion Thapa Magar",
      "country": "Qatar"
    },
    {
      "class": "9B",
      "name": "Srijaw Maharjan",
      "country": "Japan"
    },
    {
      "class": "9B",
      "name": "Prince Gurung",
      "country": "Nigeria"
    },
    {
      "class": "9C",
      "name": "Niyukta Shrestha",
      "country": "South Sudan"
    },
    {
      "class": "9C",
      "name": "Agrata Silwal",
      "country": "Syriya"
    },
    {
      "class": "9C",
      "name": "Kripisha Thapa",
      "country": "Switzerland"
    },
    {
      "class": "9C",
      "name": "Ansh Gupta",
      "country": "Ukraine"
    },
    {
      "class": "9C",
      "name": "Deep Kiran Neupane",
      "country": "Bangladesh"
    },
    {
      "class": "9C",
      "name": "Kastup Pant",
      "country": "UK"
    },
    {
      "class": "9C",
      "name": "Priyajala Dhungana",
      "country": "India"
    },
    {
      "class": "9C",
      "name": "Sujay Joshi",
      "country": "Iran"
    },
    {
      "class": "9C",
      "name": "Zara Gurung",
      "country": "Turkey"
    }
  ],
  "ecosoc": [
    {
      "class": "9A",
      "name": "Ayushman Dahal",
      "country": "USA"
    },
    {
      "class": "9A",
      "name": "Shayana Khakurel",
      "country": "Argentina"
    },
    {
      "class": "9A",
      "name": "Anuska Adhikari",
      "country": "Brazil"
    },
    {
      "class": "9A",
      "name": "Manushree Adhikari Chandani",
      "country": "China"
    },
    {
      "class": "9A",
      "name": "Phinjo Norbu Sherpa",
      "country": "Colombia"
    },
    {
      "class": "9A",
      "name": "Roneev Udas",
      "country": "DPRK"
    },
    {
      "class": "9A",
      "name": "Shara June Maharjan",
      "country": "Ethiopia"
    },
    {
      "class": "9A",
      "name": "Sulav Jung Basnet",
      "country": "France"
    },
    {
      "class": "9B",
      "name": "Sauravi Shrestha",
      "country": "Germany"
    },
    {
      "class": "9B",
      "name": "Pratez Dangi",
      "country": "India"
    },
    {
      "class": "9B",
      "name": "Mikel Shrestha",
      "country": "Iran"
    },
    {
      "class": "9B",
      "name": "Anshuman Nanda Baidya",
      "country": "Japan"
    },
    {
      "class": "9B",
      "name": "Binayak Bastola",
      "country": "Myanmar"
    },
    {
      "class": "9B",
      "name": "Krish Pandey",
      "country": "Pakistan"
    },
    {
      "class": "9B",
      "name": "Praniva Maharjan",
      "country": "Poland"
    },
    {
      "class": "9B",
      "name": "Shaanvi Shrestha",
      "country": "Russia"
    },
    {
      "class": "9B",
      "name": "Sugat Subedi",
      "country": "Saudi Arabia"
    },
    {
      "class": "9C",
      "name": "Selina Kandel",
      "country": "South Africa"
    },
    {
      "class": "9C",
      "name": "Jashmin Subedi",
      "country": "South Korea"
    },
    {
      "class": "9C",
      "name": "Aaditya Raj Rimal",
      "country": "Sri Lanka"
    },
    {
      "class": "9C",
      "name": "Arogya Aryal",
      "country": "Ukraine"
    },
    {
      "class": "9C",
      "name": "Dipman Karki",
      "country": "UK"
    },
    {
      "class": "9C",
      "name": "Nickson Shahi",
      "country": "Afghanistan"
    },
    {
      "class": "9C",
      "name": "Riya Manandhar",
      "country": "Canada"
    },
    {
      "class": "9C",
      "name": "Shashwoat Gautam",
      "country": "Mexico"
    }
  ],
  "disec": [
    {
      "class": "9A",
      "name": "Aashima Bhattarai",
      "country": "USA"
    },
    {
      "class": "9A",
      "name": "Sanket K.C.",
      "country": "Belarus"
    },
    {
      "class": "9A",
      "name": "Prakalpa Singh Basnyat",
      "country": "Pakistan"
    },
    {
      "class": "9A",
      "name": "Aarav Poudel",
      "country": "Sudan"
    },
    {
      "class": "9A",
      "name": "Kendrika Khadka",
      "country": "DPRK"
    },
    {
      "class": "9A",
      "name": "Nensee Syangbo Tamang",
      "country": "France"
    },
    {
      "class": "9A",
      "name": "Samrat Khanal",
      "country": "India"
    },
    {
      "class": "9A",
      "name": "Soval Kunwar",
      "country": "Iran"
    },
    {
      "class": "9B",
      "name": "Saya Luitel",
      "country": "Israel"
    },
    {
      "class": "9B",
      "name": "Shanvi Rajbhandari",
      "country": "Japan"
    },
    {
      "class": "9B",
      "name": "Arpita Maharjan",
      "country": "Lebanon"
    },
    {
      "class": "9B",
      "name": "Divyesh Subedi",
      "country": "Nepal"
    },
    {
      "class": "9B",
      "name": "Nirav Chapagai",
      "country": "Brazil"
    },
    {
      "class": "9B",
      "name": "Sahil Raj Thapa",
      "country": "Palestine"
    },
    {
      "class": "9B",
      "name": "Soham Paudel",
      "country": "UK"
    },
    {
      "class": "9B",
      "name": "Tsering Lhamu Lama",
      "country": "Saudi Arabia"
    },
    {
      "class": "9C",
      "name": "Sadikshya Bhattarai",
      "country": "China"
    },
    {
      "class": "9C",
      "name": "Sabhya Devkota",
      "country": "Russia"
    },
    {
      "class": "9C",
      "name": "Bhumika Dahal",
      "country": "Ukraine"
    },
    {
      "class": "9C",
      "name": "Adhyata Paudel",
      "country": "Afghanistan"
    },
    {
      "class": "9C",
      "name": "Arpita Rijal",
      "country": "Yemen"
    },
    {
      "class": "9C",
      "name": "Hridaya Raj K.C.",
      "country": "Italy"
    },
    {
      "class": "9C",
      "name": "Soumya Shrestha",
      "country": "Germany"
    },
    {
      "class": "9C",
      "name": "Sukson Khadka",
      "country": "Iraq"
    }
  ],
  "unep": [
    {
      "class": "9A",
      "name": "Reewaz Paudel",
      "country": "Afghanistan"
    },
    {
      "class": "9A",
      "name": "Ritisha Tiwari",
      "country": "Bangladesh"
    },
    {
      "class": "9A",
      "name": "Karma Ongyal Gurung",
      "country": "Canada"
    },
    {
      "class": "9A",
      "name": "Pranab Bajracharya",
      "country": "DPRK"
    },
    {
      "class": "9A",
      "name": "Sammunat Regmi",
      "country": "France"
    },
    {
      "class": "9A",
      "name": "Shubhatmika Ghimire",
      "country": "Brazil"
    },
    {
      "class": "9A",
      "name": "Yudin Thapa Magar",
      "country": "Germany"
    },
    {
      "class": "9A",
      "name": "Subrat Raut",
      "country": "Kenya"
    },
    {
      "class": "9B",
      "name": "Bishesh Bhatt",
      "country": "Iran"
    },
    {
      "class": "9B",
      "name": "Ariva Shrestha",
      "country": "India"
    },
    {
      "class": "9B",
      "name": "Bivuti Pudasaini",
      "country": "Israel"
    },
    {
      "class": "9B",
      "name": "Kristina Gurung",
      "country": "Malaysia"
    },
    {
      "class": "9B",
      "name": "Pranzole Mahara Chhetri",
      "country": "Nepal"
    },
    {
      "class": "9B",
      "name": "Ayesha Giri",
      "country": "Mexico"
    },
    {
      "class": "9B",
      "name": "Yangtsen Tsomo Baijee",
      "country": "Australia"
    },
    {
      "class": "9B",
      "name": "Shreeti Baral",
      "country": "Norway"
    },
    {
      "class": "9C",
      "name": "Savannah Thapaliya",
      "country": "Philippines"
    },
    {
      "class": "9C",
      "name": "Adhrit Regmi",
      "country": "China"
    },
    {
      "class": "9C",
      "name": "Supreme Chapagain",
      "country": "Russia"
    },
    {
      "class": "9C",
      "name": "Aayan Maharjan",
      "country": "South Africa"
    },
    {
      "class": "9C",
      "name": "Arpita Lamichhane",
      "country": "United Arab Emirates"
    },
    {
      "class": "9C",
      "name": "Falak K.C.",
      "country": "United Kingdom"
    },
    {
      "class": "9C",
      "name": "Nivaan Jung Adhikari",
      "country": "Ukraine"
    },
    {
      "class": "9C",
      "name": "Sejal Adhikari",
      "country": "United States of America"
    }
  ]
}

export const nationalAllocations: Record<string, NationalRow[]> = {
  "lp1": [
    {
      "name": "Shivatmika Bhatta",
      "delegation": "Ravi Lamichhane",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Aarna Shrestha",
      "delegation": "Sita Badi",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Aashvi Chalise",
      "delegation": "Sobita Gautam",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Ayaan Upreti",
      "delegation": "Biraj Bhakta Shrestha",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Ayub Lamsal",
      "delegation": "Balendra Shah",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Bhaswan Man",
      "delegation": "Shishir Khanal",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Bigyapti Khanal",
      "delegation": "Gita Chaudhary",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Binaz Khadka",
      "delegation": "Manish Jha",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Deepsana Tuladhar",
      "delegation": "Jagadish Khrel",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Jaisna Gurung",
      "delegation": "Pratibha Rawal",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Prinsha Shrestha",
      "delegation": "Dr. Swornim Wagle",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Kavin Neupane",
      "delegation": "Sunil Lamsal",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Sandipta Rimal",
      "delegation": "Swasmit Pokhrel",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Krelina Shrestha",
      "delegation": "Gauri Kumari",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Mission G.C.",
      "delegation": "Khdak Raj Poudel",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Suprim Subedi",
      "delegation": "Bikram Timalsina",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Sophiya Lama",
      "delegation": "Nisha Mehata",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Prasanna Adhikari",
      "delegation": "Sudhan Gurung",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Prasiddha Rajak",
      "delegation": "Aarjunnarsingh K.C.",
      "party": "Nepali Congress (NC)"
    },
    {
      "name": "Kanvi K.C",
      "delegation": "Gita Gurung",
      "party": "Nepali Congress (NC)"
    },
    {
      "name": "Kerin Dhakal",
      "delegation": "Bharat Kumar Swar",
      "party": "Nepali Congress (NC)"
    },
    {
      "name": "Aarav Lamichhane",
      "delegation": "Nishkal Rai",
      "party": "Nepali Congress (NC)"
    },
    {
      "name": "Tenzin Yiwang",
      "delegation": "Bhishma Raj Aangden",
      "party": "Nepali Congress (NC)"
    },
    {
      "name": "Suvam Kiju",
      "delegation": "Yogesh Gauchan",
      "party": "Nepali Congress (NC)"
    },
    {
      "name": "Samyog Chaurel",
      "delegation": "Padma Kumari Aryal",
      "party": "Communist Party of Nepal (CPNUML)"
    },
    {
      "name": "Pratyush Bartaula",
      "delegation": "Ram Bahadur Thapa",
      "party": "Communist Party of Nepal (CPNUML)"
    },
    {
      "name": "Sanish Karki",
      "delegation": "Suhang Nemwang",
      "party": "Communist Party of Nepal (CPNUML)"
    },
    {
      "name": "Pema Yangzom",
      "delegation": "Ain Bahadur Mahar",
      "party": "Communist Party of Nepal (CPNUML)"
    },
    {
      "name": "Prapti Subedi",
      "delegation": "Mohammad Istiyak Rai",
      "party": "Communist Party of Nepal (CPNUML)"
    },
    {
      "name": "Sabuj Jung Dhakal",
      "delegation": "Puspa Kamal Dahal",
      "party": "Nepal Communist Party (NCP)"
    },
    {
      "name": "Rachit Ojha",
      "delegation": "Barsha Man Pun",
      "party": "Nepal Communist Party (NCP)"
    },
    {
      "name": "Samrat Lamichhane",
      "delegation": "Harka Raj Rai",
      "party": "Shram Sanskriti Party (SSP)"
    },
    {
      "name": "Sulav Thapaliya",
      "delegation": "Aambika Devi Sangraula",
      "party": "Shram Sanskriti Party (SSP)"
    },
    {
      "name": "Siddhima Kansakar",
      "delegation": "Gyan Badur Shah",
      "party": "Rastriya Prajatra Party (RPP)"
    },
    {
      "name": "Prapti Parajuli",
      "delegation": "Khushbu Oli",
      "party": "Rastriya Prajatra Party (RPP)"
    }
  ],
  "lp2": [
    {
      "name": "Aabiskar Giri",
      "delegation": "Pratibha Rawal",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Anjali Bhandari",
      "delegation": "Sobita Gautam",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Anmol Kadayat",
      "delegation": "Manish Jha",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Sarbagya Raj Subedi",
      "delegation": "Pratibha Rawal",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Saina San Thakali",
      "delegation": "Jagadish Khrel",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Tenzin Gole Tamang",
      "delegation": "Bikram Timalsina",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Krisha Lama",
      "delegation": "Shishir Khanal",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Kristina Lama",
      "delegation": "Sita Badi",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Rhydam Panta",
      "delegation": "Sunil Lamsal",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Kritesh Maharjan",
      "delegation": "Biraj Bhakta Shrestha",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Sahaz Subedi",
      "delegation": "Swasmit Pokhrel",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Manjul Pratap Ghimire",
      "delegation": "Balendra Shah",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Nizma Maharjan",
      "delegation": "Gauri Kumari",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Sirika Dangol",
      "delegation": "Gita Chaudhary",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Pranshi Bagale",
      "delegation": "Nisha Mehata",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Prasanna Puri",
      "delegation": "Ravi Lamichhane",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Prayush Man Tuladhar",
      "delegation": "Sudhan Gurung",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Priyanshu Lama",
      "delegation": "Khdak Raj Poudel",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Ratish Bhandari",
      "delegation": "Swornim Wagle",
      "party": "RSP ( Rastriya Swotantra Party)"
    },
    {
      "name": "Suhana Budhathoki",
      "delegation": "Bhishma Raj Aangdembe",
      "party": "Nepal Congress"
    },
    {
      "name": "Rohan Tamrakar",
      "delegation": "Nishkal Rai",
      "party": "Nepal Congress"
    },
    {
      "name": "Sarthak Miringching",
      "delegation": "Gita Gurung",
      "party": "Nepal Congress"
    },
    {
      "name": "Soubhagya Chandra Mahat",
      "delegation": "Aarjunnarsingh K.C",
      "party": "Nepal Congress"
    },
    {
      "name": "Liyon Gurung",
      "delegation": "Bharat Kumar Swar",
      "party": "Nepal Congress"
    },
    {
      "name": "Khukuni Rai",
      "delegation": "Yogesh Gauchan",
      "party": "Nepal Congress"
    },
    {
      "name": "Pallav Mahat",
      "delegation": "Ram Bahadur Thapa",
      "party": "Communist Party of Nepal (CPNUML)"
    },
    {
      "name": "Kritagya Nepal",
      "delegation": "Mohammad Istiyak Rai",
      "party": "Communist Party of Nepal (CPNUML)"
    },
    {
      "name": "Sulav Ghimire",
      "delegation": "Padma Kumari Aryal",
      "party": "Communist Party of Nepal (CPNUML)"
    },
    {
      "name": "Sneha Gurung",
      "delegation": "Ain Bahadur Mahar",
      "party": "Communist Party of Nepal (CPNUML)"
    },
    {
      "name": "Somiya Gupta",
      "delegation": "Suhang Nemwang",
      "party": "Communist Party of Nepal (CPNUML)"
    },
    {
      "name": "Evesh K.C.",
      "delegation": "Barsha Man Pun",
      "party": "Nepal Communist Party(NCP)"
    },
    {
      "name": "Tshering Dolma Gurung",
      "delegation": "Pushpa Kamal Dahal",
      "party": "Nepal Communist Party(NCP)"
    },
    {
      "name": "Yuvika Adhikari",
      "delegation": "Harka Raj Rai",
      "party": "Shram Sanskriti Party (SSP)"
    },
    {
      "name": "Saija Thapa",
      "delegation": "Aambika Devi Sangraula",
      "party": "Shram Sanskriti Party (SSP)"
    },
    {
      "name": "Gaurav Dahal",
      "delegation": "Gyan Badur Shahi",
      "party": "Rastriya Prajatantra Party (RPP)"
    },
    {
      "name": "Season Singh",
      "delegation": "Khushbu Oli",
      "party": "Rastriya Prajatantra Party (RPP)"
    }
  ],
  "lp3": [
    {
      "name": "Sidhanta Bohara",
      "delegation": "Sobita Gautam",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Uplabdhi Bartaula",
      "delegation": "Ravi Lamichhane",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Aayaz Ghole",
      "delegation": "Manish Jha",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Suprem Sharma Chalise",
      "delegation": "Balendra shah",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Prasiddhi Khanal",
      "delegation": "Biram Timalsina",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Atharba Simkhada",
      "delegation": "Swasmit Pokhrel",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Bishesh Achyut Bhandari",
      "delegation": "Shishir Khanal",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Sejan Lal Shrestha",
      "delegation": "Jagadish Khrel",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Rashika K.C.",
      "delegation": "Pratibha Rawal",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Dipesh Osti",
      "delegation": "Biraj Bhakta Shrestha",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Doreen Shrestha",
      "delegation": "Bharat Kumar Swar",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Dridhata Khanal",
      "delegation": "Sunil Lamsal",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Kabya Maharjan",
      "delegation": "Gauri Kumari",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Kairavin Tuladhar",
      "delegation": "Gita Chaudhary",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Kashvi Pantha",
      "delegation": "Nisha Mehata",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Leniska Shrestha",
      "delegation": "Sita Badi",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Medha Ghimire",
      "delegation": "Sudhan Gurung",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Nirmit Pradhan",
      "delegation": "Khdak Raj Poudel",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Pallabi Neupane",
      "delegation": "Swornim wagle",
      "party": "Rastriya Swatantra Party (RSP)"
    },
    {
      "name": "Pasang Lama Sherpa",
      "delegation": "Nishkal Rai",
      "party": "Nepali Congress (NC)"
    },
    {
      "name": "Pranay Gopal K.C.",
      "delegation": "Gita Gurung",
      "party": "Nepali Congress (NC)"
    },
    {
      "name": "Doreen Shrestha",
      "delegation": "Bharat Kumar Swar",
      "party": "Nepali Congress (NC)"
    },
    {
      "name": "Swapnil Dev Giri",
      "delegation": "Aarjunnarsingh K.C.",
      "party": "Nepali Congress (NC)"
    },
    {
      "name": "Tanuj Gauchan",
      "delegation": "Yogesh Gauchan",
      "party": "Nepali Congress (NC)"
    },
    {
      "name": "Shristina Dura Pulami",
      "delegation": "Bhishma Raj Aangdembe",
      "party": "Nepali Congress (NC)"
    },
    {
      "name": "Aashra Shakya",
      "delegation": "Ram Bahadur Thapa",
      "party": "Communist Party of Nepal (CPNUML)"
    },
    {
      "name": "Digant Shrestha",
      "delegation": "Mohammad Istiyak Rai",
      "party": "Communist Party of Nepal (CPNUML)"
    },
    {
      "name": "Shovan Khadka",
      "delegation": "Padma Kumari Aryal",
      "party": "Communist Party of Nepal (CPNUML)"
    },
    {
      "name": "Samyog Churel",
      "delegation": "Ain Bahadur Mahar",
      "party": "Communist Party of Nepal (CPNUML)"
    },
    {
      "name": "Dibya Pudasain",
      "delegation": "Suhang Nemwang",
      "party": "Communist Party of Nepal (CPNUML)"
    },
    {
      "name": "Aaradhya Bharati",
      "delegation": "Pushpa Kamal Dahal",
      "party": "Nepal Communist Party (NCP)"
    },
    {
      "name": "Alison Moktan",
      "delegation": "Barsha Man Pun",
      "party": "Nepal Communist Party (NCP)"
    },
    {
      "name": "Pratham Adhikari",
      "delegation": "Aambika devi Sangraula",
      "party": "Shram Sanskriti Party (SSP)"
    },
    {
      "name": "Rishav Mainali",
      "delegation": "Harka Raj Rai",
      "party": "Shram Sanskriti Party (SSP)"
    },
    {
      "name": "Rajashwi Pradhan",
      "delegation": "Khushbu Oli",
      "party": "Rastriya Prajjatra Party (RPP)"
    },
    {
      "name": "Anjas Khanal",
      "delegation": "Gyan Badur Shahi",
      "party": "Rastriya Prajjatra Party (RPP)"
    }
  ]
}

export function getAllocation(slug: string) {
  if (slug in internationalAllocations) {
    return { type: "international" as const, rows: internationalAllocations[slug] }
  }
  if (slug in nationalAllocations) {
    return { type: "national" as const, rows: nationalAllocations[slug] }
  }
  return null
}
