export type NewsSession = "final" | "second" | "first";

export type NewspaperArticle = {
  slug: string;
  session: NewsSession;
  committee: string;
  committeeSlug: string;
  committeeAbbr: string;
  headline: string;
  dek: string;
  body: string[];
  image: string;
  imageAlt: string;
  caption: string;
  author: string;
  date: string;
  page: 2 | 3;
  kicker?: string;
  pullQuote?: string;
  credit?: string;
  featured?: boolean;
};

export const sessions: { id: NewsSession; label: string; edition: string; date: string }[] = [
  { id: "final", label: "Final Session", edition: "Vol. XIV · No. 3", date: "Closing Day · Kathmandu" },
  { id: "second", label: "Second Session", edition: "Vol. XIV · No. 2", date: "Mid-Conference · Kathmandu" },
  { id: "first", label: "First Session", edition: "Vol. XIV · No. 1", date: "Opening Day · Kathmandu" },
];

export const newspaperArticles: NewspaperArticle[] = [
  {
    slug: "lp1-final-chamber-settles",
    session: "final",
    committee: "Legislative Parliament I",
    committeeSlug: "lp1",
    committeeAbbr: "LP I",
    headline: "The chamber settles on a narrower bill",
    dek: "After two days of coalition arithmetic, LP I sent a trimmed text to the floor rather than a louder one.",
    body: [
      "By the last sitting, Legislative Parliament I had stopped performing for the gallery. Motions arrived shorter. Interruptions arrived later. The bill that survived was the one that could still be recognised by every bench that had argued over it.",
      "The chair kept the clock honest and the aisle open. What changed was not the topic but the temperature: delegates who had spent the second session defending whole chapters now bargained over sentences.",
      "A late amendment on implementation language passed without applause. That, more than any speech, told the room it had finished its work.",
    ],
    image: "/images/gallery-gavel.jpg",
    imageAlt: "A wooden gavel resting on a formal desk after session",
    caption: "The gavel waits while the last clause is read.",
    author: "TESMUN Press Corps",
    date: "Closing Day",
    page: 2,
    kicker: "Parliament",
    pullQuote: "The bill that survived was the one the room could still recognise.",
  },
  {
    slug: "lp2-final-majority-holds",
    session: "final",
    committee: "Legislative Parliament II",
    committeeSlug: "lp2",
    committeeAbbr: "LP II",
    headline: "A working majority, held by a clause",
    dek: "LP II closed with a majority intact — and a single sentence that nearly undid it.",
    body: [
      "Legislative Parliament II spent its final hours defending a majority that had looked comfortable at lunch and fragile by tea. The trouble was not numbers. It was a clause on oversight that two parties read in opposite directions.",
      "Unmoderated time did the real drafting. When the house reconvened, the sentence had been recast as a review rather than a veto. The vote held.",
      "Delegates left with the unusual satisfaction of a chamber that had argued itself into something it could live with.",
    ],
    image: "/images/gallery-delegates.jpg",
    imageAlt: "Delegates seated around a formal table in discussion",
    caption: "The majority was rebuilt in conversation, not in the speech list.",
    author: "TESMUN Press Corps",
    date: "Closing Day",
    page: 2,
    kicker: "Parliament",
  },
  {
    slug: "lp3-final-crossbench",
    session: "final",
    committee: "Legislative Parliament III",
    committeeSlug: "lp3",
    committeeAbbr: "LP III",
    headline: "The crossbench writes the last line",
    dek: "LP III’s closing text belonged to neither front bench. That was the point.",
    body: [
      "In Legislative Parliament III the final sitting belonged to the seats between the two large blocs. A short, carefully worded insertion on public consultation became the price of passage.",
      "Neither side claimed victory. Both claimed authorship of a phrase. The chair allowed the room that small vanity and moved the question.",
      "The resulting act is modest on paper and large in method: it was built by people who had to stay in the room after the vote.",
    ],
    image: "/images/news-handshake.jpg",
    imageAlt: "A formal handshake across a conference table",
    caption: "Agreement arrived as a phrase both sides could carry.",
    author: "TESMUN Press Corps",
    date: "Closing Day",
    page: 2,
    kicker: "Parliament",
  },
  {
    slug: "hrc-final-rights-language",
    session: "final",
    committee: "Human Rights Council",
    committeeSlug: "hrc",
    committeeAbbr: "HRC",
    headline: "Rights language, made to travel",
    dek: "The Council adopted a text that can leave the hall without losing its meaning.",
    body: [
      "The Human Rights Council’s last session was an exercise in translation. Delegates kept asking the same question of every paragraph: will this still mean something outside this room?",
      "Operative clauses that had been ornamental were cut. Those that named duties were kept. A proposed reference to monitoring survived because it named who would read the report, not only that a report should exist.",
      "The adopted resolution is not the longest the Council considered. It is the one most likely to be quoted later without embarrassment.",
    ],
    image: "/images/gallery-debate.jpg",
    imageAlt: "A young speaker addressing a formal discussion from a microphone",
    caption: "The floor asked not for volume, but for language that could travel.",
    author: "TESMUN Press Corps",
    date: "Closing Day",
    page: 2,
    kicker: "Council",
    pullQuote: "Will this still mean something outside this room?",
    featured: true,
    credit: "Photograph · TESMUN Press Corps",
  },
  {
    slug: "disec-final-arms-pause",
    session: "final",
    committee: "Disarmament and International Security Committee",
    committeeSlug: "disec",
    committeeAbbr: "DISEC",
    headline: "A pause, written into the record",
    dek: "DISEC closed not with a grand ban, but with a timetable the room could defend.",
    body: [
      "DISEC’s final text does not pretend the world is simpler than it is. It names a pause, a reporting cycle and a review. Delegates who had arrived with maximalist drafts left with something they could explain at home.",
      "The turning point was a question from a smaller delegation: who verifies, and when? Once that was answered in writing, larger blocs found they could live with less rhetoric.",
      "Security, the chair reminded the room, is often a calendar as much as a principle.",
    ],
    image: "/images/gallery-flags.jpg",
    imageAlt: "A speaker at a podium during a formal conference address",
    caption: "The committee chose a timetable over a slogan.",
    author: "TESMUN Press Corps",
    date: "Closing Day",
    page: 3,
    kicker: "Security",
  },
  {
    slug: "ecosoc-final-shared-ledger",
    session: "final",
    committee: "Economic and Social Council",
    committeeSlug: "ecosoc",
    committeeAbbr: "ECOSOC",
    headline: "A shared ledger for a shared problem",
    dek: "ECOSOC’s closing resolution treats development as an account that must be kept, not a speech that must be given.",
    body: [
      "The Economic and Social Council spent its last hours arguing about measurement. Not because numbers are more important than people, but because without them the room could not tell whether it had agreed at all.",
      "The adopted text pairs a financing window with a public ledger of commitments. Several delegations called it unglamorous. The chair called it usable.",
      "If the conference is remembered for one practical invention, it may be this: a table that outlasts the session that produced it.",
    ],
    image: "/images/news-notes.jpg",
    imageAlt: "A person writing notes during a formal meeting",
    caption: "The most consequential page was a table of commitments.",
    author: "TESMUN Press Corps",
    date: "Closing Day",
    page: 3,
    kicker: "Development",
  },
  {
    slug: "unep-final-common-basin",
    session: "final",
    committee: "United Nations Environment Programme",
    committeeSlug: "unep",
    committeeAbbr: "UNEP",
    headline: "One basin, two calendars, a single text",
    dek: "UNEP found a way to keep climate ambition and local water politics in the same paragraph.",
    body: [
      "UNEP’s closing debate sounded like two conferences until a working paper treated a river basin as both a climate fact and a livelihood. After that, the room stopped choosing between them.",
      "The resolution asks for a joint monitoring season rather than a single deadline. Delegates from opposite climates recognised their own weather in the same sentence.",
      "It is a small diplomatic trick and a large one: make the map more specific, and the argument becomes possible.",
    ],
    image: "/images/gallery-assembly.jpg",
    imageAlt: "Flags of member countries along a ceremonial avenue",
    caption: "Specific geography made a general argument possible.",
    author: "TESMUN Press Corps",
    date: "Closing Day",
    page: 3,
    kicker: "Environment",
  },
  {
    slug: "lp1-second-coalition-tests",
    session: "second",
    committee: "Legislative Parliament I",
    committeeSlug: "lp1",
    committeeAbbr: "LP I",
    headline: "Coalitions tested in the tea break",
    dek: "LP I’s second sitting moved the real debate into the corridor — and then back again.",
    body: [
      "The second session of Legislative Parliament I was a study in how majorities are borrowed. A bloc that had looked settled on day one discovered it needed three more voices, and those voices had conditions.",
      "Points of information multiplied. So did handwritten notes. The chair allowed one extra unmoderated caucus and then closed the list.",
      "By adjournment the text was longer and clearer. That is not always the same as progress, but in this room it was.",
    ],
    image: "/images/about-purpose.png",
    imageAlt: "A delegate’s hand resting on a wooden podium",
    caption: "The podium waited while the corridor did the counting.",
    author: "TESMUN Press Corps",
    date: "Mid-Conference",
    page: 2,
    kicker: "Parliament",
  },
  {
    slug: "lp2-second-procedure-bites",
    session: "second",
    committee: "Legislative Parliament II",
    committeeSlug: "lp2",
    committeeAbbr: "LP II",
    headline: "Procedure, used as a tool rather than a shield",
    dek: "LP II learned that a well-timed motion can be more persuasive than a long speech.",
    body: [
      "Legislative Parliament II’s second session belonged to delegates who had read the rules twice. A motion to divide the question split a sprawling draft into pieces the house could actually vote on.",
      "Some called it tactical. The chair called it housekeeping. Either way, the room moved.",
      "What remained on the table overnight was smaller, sharper and much harder to ignore.",
    ],
    image: "/images/committees-preview.png",
    imageAlt: "A gavel resting beside folded country nameplates",
    caption: "The nameplates stayed still. The draft did not.",
    author: "TESMUN Press Corps",
    date: "Mid-Conference",
    page: 2,
    kicker: "Parliament",
  },
  {
    slug: "lp3-second-whispered-amendment",
    session: "second",
    committee: "Legislative Parliament III",
    committeeSlug: "lp3",
    committeeAbbr: "LP III",
    headline: "The amendment that arrived in a whisper",
    dek: "LP III’s most important sentence was not delivered from the floor.",
    body: [
      "A scrap of paper crossed three desks in Legislative Parliament III before it became an official amendment. By the time it was read aloud, half the room had already decided it was reasonable.",
      "That is either undemocratic or extremely democratic, depending on how one feels about tea. The chair accepted it, the house debated it, and the clause stayed.",
      "Second sessions are for this kind of work: the unglamorous transfer of a good idea from a margin to a motion.",
    ],
    image: "/images/gallery-podium.jpg",
    imageAlt: "An empty conference room with a podium and rows of chairs",
    caption: "The floor was quieter than the notes passing across it.",
    author: "TESMUN Press Corps",
    date: "Mid-Conference",
    page: 2,
    kicker: "Parliament",
    pullQuote: "The most important sentence was not delivered from the floor.",
    featured: true,
    credit: "Photograph · TESMUN Press Corps",
  },
  {
    slug: "hrc-second-witness-gap",
    session: "second",
    committee: "Human Rights Council",
    committeeSlug: "hrc",
    committeeAbbr: "HRC",
    headline: "The Council argues over who is heard",
    dek: "HRC’s second sitting turned on a single procedural question: whose testimony enters the record.",
    body: [
      "The Human Rights Council spent the afternoon on access. Not to the room — to the document. A proposal to annex civil-society statements split delegations that had agreed on almost everything else.",
      "Supporters said a council that cannot hear cannot protect. Opponents said a council that cannot filter cannot decide. The compromise was a summary, not a silence.",
      "It was an unsatisfying solution and an honest one. The record now shows both the argument and the people it tried to include.",
    ],
    image: "/images/news-featured.jpg",
    imageAlt: "A close-up of printed newspapers",
    caption: "The record became the argument.",
    author: "TESMUN Press Corps",
    date: "Mid-Conference",
    page: 2,
    kicker: "Council",
  },
  {
    slug: "disec-second-definitions",
    session: "second",
    committee: "Disarmament and International Security Committee",
    committeeSlug: "disec",
    committeeAbbr: "DISEC",
    headline: "Definitions before disarmament",
    dek: "DISEC refused to vote on verbs until it had agreed on nouns.",
    body: [
      "The second session of DISEC sounded pedantic until it became obvious that nobody shared a definition of ‘stockpile’. Once that word was pinned down, three operative clauses wrote themselves.",
      "Delegates who had prepared soaring speeches discovered that a glossary is also diplomacy.",
      "The working paper that left the room overnight was dull in the best sense: it could be implemented by people who were not in the hall.",
    ],
    image: "/images/gallery-library.jpg",
    imageAlt: "Eyeglasses resting on a stack of research notebooks",
    caption: "The glossary did more work than the rhetoric.",
    author: "TESMUN Press Corps",
    date: "Mid-Conference",
    page: 3,
    kicker: "Security",
  },
  {
    slug: "ecosoc-second-finance-floor",
    session: "second",
    committee: "Economic and Social Council",
    committeeSlug: "ecosoc",
    committeeAbbr: "ECOSOC",
    headline: "Finance reaches the floor, finally",
    dek: "ECOSOC stopped talking around money and put a figure on the table.",
    body: [
      "Until the second session, the Economic and Social Council had been eloquent about poverty and vague about who would pay. A small delegation changed the weather by asking for a number.",
      "The number that appeared was provisional, bracketed and immediately contested. It was also the first honest sentence of the day.",
      "From that point the debate had a floor. Delegates could raise it, lower it or walk away from it — but they could no longer pretend it was not there.",
    ],
    image: "/images/about-vision.png",
    imageAlt: "An empty conference table lined with chairs and flags",
    caption: "Once a figure was named, the empty chairs felt less theoretical.",
    author: "TESMUN Press Corps",
    date: "Mid-Conference",
    page: 3,
    kicker: "Development",
  },
  {
    slug: "unep-second-seasonal-truth",
    session: "second",
    committee: "United Nations Environment Programme",
    committeeSlug: "unep",
    committeeAbbr: "UNEP",
    headline: "A seasonal truth enters the draft",
    dek: "UNEP’s second sitting insisted that climate text name a month, not only a century.",
    body: [
      "UNEP’s working paper gained a calendar. Delegates from monsoon and dry-season capitals refused to sign a paragraph that treated the year as an even surface.",
      "The amendment is three words long and changes the entire document. Implementation, it says, shall be seasonal.",
      "It is the kind of specificity that makes environmental diplomacy less poetic and more useful.",
    ],
    image: "/images/gallery-kathmandu.jpg",
    imageAlt: "Silhouette of people at a historic pavilion in Kathmandu at dusk",
    caption: "Local weather refused to stay out of a global draft.",
    author: "TESMUN Press Corps",
    date: "Mid-Conference",
    page: 3,
    kicker: "Environment",
  },
  {
    slug: "lp1-first-opening-benches",
    session: "first",
    committee: "Legislative Parliament I",
    committeeSlug: "lp1",
    committeeAbbr: "LP I",
    headline: "The benches find their voices",
    dek: "LP I opened with ceremony, then with the first real test of who would speak for whom.",
    body: [
      "Legislative Parliament I began as these houses always do: with introductions that sounded like promises. The first contested motion arrived sooner than expected and told the room who had done the reading.",
      "A point of order, handled cleanly, did more for the chair’s authority than any opening remark. After that, the benches settled.",
      "The draft on the table is still a sketch. The habits of the house are already visible.",
    ],
    image: "/images/gallery-campus.jpg",
    imageAlt: "Tree-lined courtyard between academic buildings",
    caption: "Before the first motion, the grounds were quieter than the chamber would be.",
    author: "TESMUN Press Corps",
    date: "Opening Day",
    page: 2,
    kicker: "Parliament",
  },
  {
    slug: "lp2-first-rules-tested",
    session: "first",
    committee: "Legislative Parliament II",
    committeeSlug: "lp2",
    committeeAbbr: "LP II",
    headline: "Rules, tested before they are trusted",
    dek: "LP II’s opening sitting was less about the bill than about whether the house would keep its own clock.",
    body: [
      "The first hour of Legislative Parliament II belonged to procedure. Delegates tried the yield, the right of reply and the patience of the chair.",
      "None of this was delay for its own sake. A house that cannot run its clock cannot run a country, even a simulated one.",
      "By adjournment a working paper existed, and so did a shared sense that the rules were real.",
    ],
    image: "/images/mottobg.png",
    imageAlt: "Atmospheric hall lighting used for the TESMUN motto",
    caption: "The first sitting was a rehearsal for seriousness.",
    author: "TESMUN Press Corps",
    date: "Opening Day",
    page: 2,
    kicker: "Parliament",
  },
  {
    slug: "lp3-first-new-house",
    session: "first",
    committee: "Legislative Parliament III",
    committeeSlug: "lp3",
    committeeAbbr: "LP III",
    headline: "A new house learns its acoustics",
    dek: "LP III opened like a room discovering how loud it needs to be.",
    body: [
      "Legislative Parliament III is a parallel chamber, and on opening day it sounded like one: a little too formal, then a little too casual, then suddenly precise.",
      "The first speakers set a weather of courtesy. The first interruption set a weather of attention. Both will be needed.",
      "The bill introduced is ambitious. The house, for now, is still learning how to hold it.",
    ],
    image: "/images/press-hero.png",
    imageAlt: "Editorial still from the TESMUN press desk",
    caption: "Even a new house produces a record from the first hour.",
    author: "TESMUN Press Corps",
    date: "Opening Day",
    page: 2,
    kicker: "Parliament",
  },
  {
    slug: "hrc-first-agenda-set",
    session: "first",
    committee: "Human Rights Council",
    committeeSlug: "hrc",
    committeeAbbr: "HRC",
    headline: "The Council chooses its question",
    dek: "HRC’s opening was a fight over the agenda — which is to say, a fight over what counts as urgent.",
    body: [
      "The Human Rights Council spent its first sitting deciding what it would be allowed to care about. Two agenda items were proposed. Only one could lead.",
      "The choice was not cosmetic. It decided whose harm would be named first, and therefore whose remedy would be drafted under time pressure.",
      "The adopted agenda is a moral document disguised as a timetable. The rest of the conference will have to live inside it.",
    ],
    image: "/images/gallery-debate.jpg",
    imageAlt: "A speaker at a microphone during formal debate",
    caption: "The first decision was what the room would be permitted to see.",
    author: "TESMUN Press Corps",
    date: "Opening Day",
    page: 2,
    kicker: "Council",
    pullQuote: "The agenda is a moral document disguised as a timetable.",
    featured: true,
    credit: "Photograph · TESMUN Press Corps",
  },
  {
    slug: "disec-first-maps-out",
    session: "first",
    committee: "Disarmament and International Security Committee",
    committeeSlug: "disec",
    committeeAbbr: "DISEC",
    headline: "Maps on the table, positions still in the briefcase",
    dek: "DISEC opened by agreeing on geography and postponing almost everything else.",
    body: [
      "DISEC’s first session was cartographic. Delegates named regions, corridors and stockpiles before they named solutions. It was slower than some wanted and more honest than a premature draft.",
      "A few opening statements arrived fully armed with verbs. The chair thanked them and asked for nouns.",
      "Overnight, the secretariat circulated a single-page map of terms. Tomorrow’s argument will be better for it.",
    ],
    image: "/images/news-handshake.jpg",
    imageAlt: "A formal handshake during conference proceedings",
    caption: "Courtesy first. Definitions second. Verbs later.",
    author: "TESMUN Press Corps",
    date: "Opening Day",
    page: 3,
    kicker: "Security",
  },
  {
    slug: "ecosoc-first-stakes-named",
    session: "first",
    committee: "Economic and Social Council",
    committeeSlug: "ecosoc",
    committeeAbbr: "ECOSOC",
    headline: "The stakes are named, if not yet priced",
    dek: "ECOSOC opened with a shared diagnosis and a polite disagreement about the cure.",
    body: [
      "The Economic and Social Council began in unusual harmony: almost every delegation agreed the problem was real. The peace lasted until someone asked what it would cost to fix.",
      "Opening statements therefore did two jobs. They established goodwill. They also established the fault lines the next two sittings will have to walk.",
      "A background paper on financing was requested before adjournment. That request may prove to be the session’s most important sentence.",
    ],
    image: "/images/news-notes.jpg",
    imageAlt: "Notes being written during a conference session",
    caption: "Agreement on the problem lasted until the first estimate.",
    author: "TESMUN Press Corps",
    date: "Opening Day",
    page: 3,
    kicker: "Development",
  },
  {
    slug: "unep-first-weather-enters",
    session: "first",
    committee: "United Nations Environment Programme",
    committeeSlug: "unep",
    committeeAbbr: "UNEP",
    headline: "The weather enters the hall",
    dek: "UNEP’s opening statements refused to treat the environment as a metaphor.",
    body: [
      "UNEP began with specifics: a basin, a season, a crop, a coast. Delegates who had prepared generalities found themselves answering to places.",
      "The chair encouraged this. A programme that cannot name a river cannot protect one.",
      "The first working paper, promised for the second sitting, will have to keep that discipline or lose the room.",
    ],
    image: "/images/about-hero.png",
    imageAlt: "A cinematic view of a conference hall",
    caption: "The hall sounded more like a map than a manifesto.",
    author: "TESMUN Press Corps",
    date: "Opening Day",
    page: 3,
    kicker: "Environment",
  },
];

export function getSessionMeta(id: NewsSession) {
  return sessions.find((item) => item.id === id) ?? sessions[0];
}

export function articlesBySession(id: NewsSession) {
  return newspaperArticles.filter((article) => article.session === id);
}

export function getNewspaperArticle(slug: string) {
  return newspaperArticles.find((article) => article.slug === slug);
}

export function relatedNewspaperArticles(slug: string, limit = 3) {
  const current = getNewspaperArticle(slug);
  if (!current) return newspaperArticles.slice(0, limit);
  return newspaperArticles.filter((article) => article.slug !== slug && article.session === current.session).slice(0, limit);
}
